services:
  portfolio:
    build: .
    restart: always
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextapp.rule=Host(`portfolio.76.13.241.100`)"
      - "traefik.http.routers.nextapp.entrypoints=web"
      # - "traefik.http.routers.nextapp.tls.certresolver=myresolver"
      # Next.js usually runs on port 3000 inside the container
      - "traefik.http.services.nextapp.loadbalancer.server.port=3000"

networks:
  traefik-public:
    external: true